### ISSUE TITLE
Dynamic Menu

### ISSUE THREAD

**Issue by sm2x** [tomsx/nuBuilderForteCustomization#2]
This is a Wish rather than an issue,
Can it be extended to include the "Form Launchers" granted on user's access level?
This could be a lot neater alternative to existing button launchers.

**Comment by tomsx** [comment]
I guess you're talking about this quick menu?
https://github.com/tomsx/nuBuilderForteCustomization/blob/master/quickMenu.js

Would the idea be that every user can see his form launchers in this menu?

**Comment by sm2x** [comment]
Yes please the quickMenu.js, or even better if it can be converted into a full blown auto-hide Side Bar Menu with glyphs on the side (asking for too much :).

Suggested Layout:
Application Title (left) / Logo (right)
|SBM| Burger  / Breadcrumbs
|SBM| Tab Holders
|SBM| Collapsible Sections

This will modernize the UI of classic nuBuilder.

**Comment by tomsx** [comment]
Would a top navigation bar work for you? Something like this:
http://i68.tinypic.com/2nq6us6.jpg
